app/app/urls.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/08/2020 15:46.

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('config/', include('config.urls')),
    path('device/', include('device.urls')),
    path('service/', include('service.urls')),
]

# Handling errors, but only if debug is set to False and there is another server to serve staticfiles
handler400 = 'frontend.views.error_400'
handler401 = 'frontend.views.error_401'
handler403 = 'frontend.views.error_403'
handler404 = 'frontend.views.error_404'
handler500 = 'frontend.views.error_500'
handler503 = 'frontend.views.error_503'

app/customer/urls.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 31/07/2020 14:27.
from django.urls import path, include

from .views import *

app_name = "customer"

individual_patterns = ([
                           path('', IndividualCustomerView.as_view(), name='view'),
                           path('create/', IndividualCustomerCreate.as_view(), name='create'),
                           path('<int:pk>/edit/', IndividualCustomerEdit.as_view(), name='edit'),
                           path('<int:pk>/del', IndividualCustomerDel.as_view(), name='delete'),
                       ], 'individualcustomer')

juridical_patterns = ([
                          path('', JuridicalCustomerView.as_view(), name='view'),
                          path('create/', JuridicalCustomerCreate.as_view(), name='create'),
                          path('<int:pk>/edit/', JuridicalCustomerEdit.as_view(), name='edit'),
                          path('<int:pk>/del', JuridicalCustomerDel.as_view(), name='delete'),
                      ], 'juridicalcustomer')

urlpatterns = [
    path('', Customer.as_view(), name='index'),
    path('profile/<int:pk>/<int:tp>/', CustomerProfile.as_view(), name='profile'),
    path('individual/', include(individual_patterns)),
    path('juridical/', include(juridical_patterns)),
]

app/device/urls.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 12/08/2020 14:49.
from django.urls import path

from .views import *

app_name = "device"

urlpatterns = [
    # path('', DeviceIndex.as_view(), name='index'),
    path('view/', DeviceView.as_view(), name='view'),
    path('<int:cpk>/<int:ctp>/<int:pk>/profile/', DeviceProfile.as_view(), name='profile'),
    path('<int:cpk>/<int:ctp>/create/', DeviceCreate.as_view(), name='create'),
    path('<int:cpk>/<int:ctp>/<int:pk>/edit/', DeviceEdit.as_view(), name='edit'),
    path('<int:cpk>/<int:ctp>/<int:pk>/delete/', DeviceDel.as_view(), name='delete'),
]

app/frontend/urls.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/08/2020 15:18.

from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
]

app/frontend/models.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 10/08/2020 11:56.
from django.db import models


class NotificationsMessages(models.Model):
    text = models.CharField(max_length=128, blank=True, null=True)
    link = models.CharField(max_length=128, blank=True, null=True)
    show = models.BooleanField(default=True)
    important = models.BooleanField(default=False)

app/customer/forms.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/08/2020 15:11.
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field
from django import forms

from .models import *


class IndividualCustomerForm(forms.ModelForm):
    layout = Layout(
        Div(
            Div(
                Field('name', wrapper_class='col-md-12'),
                Field('email', wrapper_class='col-md-12'),
                Field('phone', wrapper_class='col-md-12'),
                Field('cellphone', wrapper_class='col-md-12'),
                Field('cpf', wrapper_class='col-md-12'),
                css_class="col-md-6"
            ),
            Div(
                Field('street', wrapper_class='col-md-12'),
                Field('number', wrapper_class='col-md-12'),
                Field('neighborhood', wrapper_class='col-md-12'),
                Field('apartment', wrapper_class='col-md-12'),
                Field('block', wrapper_class='col-md-12'),
                Field('cep', wrapper_class='col-md-12'),
                Field('city', wrapper_class='col-md-12'),
                Field('state', wrapper_class='col-md-12'),
                # Field('address_line', wrapper_class='col-md-12'),
                css_class="col-md-6"
            ),
            css_class="row"
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.disable_csrf = True
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = self.layout
        self.helper.form_class = 'form-control'
        self.helper.label_class = 'bmd-label-floating'

    class Meta:
        model = IndividualCustomer
        fields = ['name', 'email', 'phone',
                  'cpf', 'cellphone', 'street', 'number',
                  'neighborhood', 'apartment', 'block',
                  'city', 'state', 'cep', 'address_line']


class JuridicalCustomerForm(forms.ModelForm):
    layout = Layout(
        Div(
            Div(
                Field('name', wrapper_class='col-md-12'),
                Field('email', wrapper_class='col-md-12'),
                Field('phone', wrapper_class='col-md-12'),
                Field('cellphone', wrapper_class='col-md-12'),
                Field('cnpj', wrapper_class='col-md-12'),
                Field('parent_company', wrapper_class='col-md-12'),
                css_class='col-md-6'
            ),
            Div(
                Field('street', wrapper_class='col-md-12'),
                Field('number', wrapper_class='col-md-12'),
                Field('neighborhood', wrapper_class='col-md-12'),
                Field('apartment', wrapper_class='col-md-12'),
                Field('block', wrapper_class='col-md-12'),
                Field('cep', wrapper_class='col-md-12'),
                Field('city', wrapper_class='col-md-12'),
                Field('state', wrapper_class='col-md-12'),
                # Field('address_line', wrapper_class='col-md-12'),
                css_class="col-md-6"
            ),
            css_class='row'
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.disable_csrf = True
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = self.layout
        self.helper.form_class = 'form-control'
        self.helper.label_class = 'bmd-label-floating'

    class Meta:
        model = JuridicalCustomer
        fields = ['name', 'email', 'phone',
                  'cnpj',
                  'cellphone', 'street', 'number',
                  'neighborhood', 'apartment', 'block',
                  'city', 'state', 'cep',
                  'address_line', 'parent_company']

app/customer/views.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/08/2020 17:44.
from typing import Dict, Any

from django.contrib.admin.utils import NestedObjects
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django_filters.views import FilterView
from django_tables2.paginators import LazyPaginator
from django_tables2.views import SingleTableMixin

from .conf import *
from .filters import *
from .forms import *
from .tables import *
from frontend.icons import ICON_PERSON, ICON_NEW_PERSON


class CustomerProfile(LoginRequiredMixin, View):
    template = 'customer/profile.html'

    def get(self, request, pk, tp):
        obj = IndividualCustomer.objects.get(pk=pk) if tp == 0 else JuridicalCustomer.objects.get(pk=pk)
        header = HEADER_CLASS_INDIVIDUAL_CUSTOMER if tp == 0 else HEADER_CLASS_JURIDICAL_CUSTOMER
        context = {
            'config': {
                'header': header
            },
            'obj': obj,
        }
        return render(request, self.template, context)


class Customer(LoginRequiredMixin, View):
    template = 'customer/view.html'
    title = TITLE_VIEW_CUSTOMER
    subtitle = SUBTITLE_VIEW_CUSTOMER

    def get(self, request):
        links = {
            'Pessoas Físicas': {
                'Pessoa Física': {
                    'name': "Ver Todas Pessoas Físicas",
                    'link': reverse_lazy('customer:individualcustomer:view'),
                    'contextual': 'success',
                    'icon': ICON_PERSON,
                },
                'Novo Cadastro': {
                    'name': "Novo Cadastro",
                    'link': reverse_lazy('customer:individualcustomer:create'),
                    'contextual': 'primary',
                    'icon': ICON_NEW_PERSON,
                },
            },
            'Pessoas Jurídicas': {
                'Pessoa Jurídica': {
                    'name': "Ver Todas Pessoas Jurídicas",
                    'link': reverse_lazy('customer:juridicalcustomer:view'),
                    'contextual': 'success',
                    'icon': ICON_PERSON,
                },
                'Novo Cadastro': {
                    'name': "Novo Cadastro",
                    'link': reverse_lazy('customer:juridicalcustomer:create'),
                    'contextual': 'primary',
                    'icon': ICON_NEW_PERSON,
                },
            },
        }
        context = {
            'title': self.title,
            'subtitle': self.subtitle,
            'links': links
        }
        return render(request, self.template, context)


########################################################################################################################
class IndividualCustomerView(LoginRequiredMixin, PermissionRequiredMixin, SingleTableMixin, FilterView):
    model = IndividualCustomer
    table_class = IndividualCustomerTable
    filterset_class = IndividualCustomerFilter
    paginator_class = LazyPaginator
    permission_required = 'customer.view_individualcustomer'
    template_name = 'base/view.html'
    title = TITLE_VIEW_INDIVIDUAL_CUSTOMER
    subtitle = SUBTITLE_INDIVIDUAL_CUSTOMER
    new = reverse_lazy('customer:individualcustomer:create')
    back_url = reverse_lazy('customer:index')
    header_class = HEADER_CLASS_INDIVIDUAL_CUSTOMER


class IndividualCustomerCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = IndividualCustomer
    form_class = IndividualCustomerForm
    template_name = 'customer/form.html'
    permission_required = 'customer.create_individualcustomer'
    title = TITLE_CREATE_INDIVIDUAL_CUSTOMER
    subtitle = SUBTITLE_INDIVIDUAL_CUSTOMER
    header_class = HEADER_CLASS_INDIVIDUAL_CUSTOMER

    @staticmethod
    def get_back_url():
        return reverse_lazy('customer:individualcustomer:view')


class IndividualCustomerEdit(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = IndividualCustomer
    form_class = IndividualCustomerForm
    template_name = 'customer/form.html'
    permission_required = 'customer.edit_individualcustomer'
    title = TITLE_EDIT_INDIVIDUAL_CUSTOMER
    subtitle = SUBTITLE_INDIVIDUAL_CUSTOMER
    header_class = HEADER_CLASS_INDIVIDUAL_CUSTOMER


# delete all services
class IndividualCustomerDel(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = IndividualCustomer
    template_name = "base/confirm_delete.html"
    permission_required = 'customer.del_individualcustomer'
    success_url = reverse_lazy('customer:individualcustomer:view')
    title = TITLE_DEL_INDIVIDUAL_CUSTOMER
    subtitle = SUBTITLE_INDIVIDUAL_CUSTOMER
    header_class = HEADER_CLASS_INDIVIDUAL_CUSTOMER

    def get_context_data(self, **kwargs):
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        collector = NestedObjects(using='default')  # or specific database
        collector.collect([context['object']])
        to_delete = collector.nested()
        context['extra_object'] = to_delete
        return context


########################################################################################################################
class JuridicalCustomerView(LoginRequiredMixin, PermissionRequiredMixin, SingleTableMixin, FilterView):
    model = JuridicalCustomer
    table_class = JuridicalCustomerTable
    filterset_class = JuridicalCustomerFilter
    paginator_class = LazyPaginator
    permission_required = 'customer.view_juridicalcustomer'
    template_name = 'base/view.html'
    title = TITLE_VIEW_JURIDICAL_CUSTOMER
    subtitle = SUBTITLE_JURIDICAL_CUSTOMER
    new = reverse_lazy('customer:juridicalcustomer:create')
    back_url = reverse_lazy('customer:index')
    header_class = HEADER_CLASS_JURIDICAL_CUSTOMER


class JuridicalCustomerCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = JuridicalCustomer
    form_class = JuridicalCustomerForm
    template_name = 'base/form.html'
    permission_required = 'customer.create_juridicalcustomer'
    title = TITLE_CREATE_JURIDICAL_CUSTOMER
    subtitle = SUBTITLE_JURIDICAL_CUSTOMER
    header_class = HEADER_CLASS_JURIDICAL_CUSTOMER

    @staticmethod
    def get_back_url():
        return reverse_lazy('customer:juridicalcustomer:view')


class JuridicalCustomerEdit(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = JuridicalCustomer
    form_class = JuridicalCustomerForm
    template_name = 'base/form.html'
    permission_required = 'customer.edit_juridicalcustomer'
    title = TITLE_EDIT_JURIDICAL_CUSTOMER
    subtitle = SUBTITLE_JURIDICAL_CUSTOMER
    header_class = HEADER_CLASS_JURIDICAL_CUSTOMER


# delete all services
class JuridicalCustomerDel(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = JuridicalCustomer
    template_name = "base/confirm_delete.html"
    permission_required = 'customer.del_juridicalcustomer'
    success_url = reverse_lazy('customer:juridicalcustomer:view')
    title = TITLE_DEL_JURIDICAL_CUSTOMER
    subtitle = SUBTITLE_JURIDICAL_CUSTOMER
    header_class = HEADER_CLASS_JURIDICAL_CUSTOMER

    def get_context_data(self, **kwargs):
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        collector = NestedObjects(using='default')  # or specific database
        collector.collect([context['object']])
        to_delete = collector.nested()
        context['extra_object'] = to_delete
        return context

app/frontend/views.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/08/2020 15:42.

import logging

from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from .utils import *

logger = logging.getLogger(__name__)


def error_400(request, exception):
    logger.error("Error 400: [%s]" % exception)
    return render(request, '400.html', {}, status=400)


def error_401(request, exception):
    logger.error("Error 401: [%s]" % exception)
    return render(request, '401.html', {}, status=401)


def error_403(request, exception):
    logger.error("Error 403: [%s]" % exception)
    return render(request, '403.html', {}, status=403)


def error_404(request, exception):
    logger.error("Error 404: [%s]" % exception)
    return render(request, '404.html', {}, status=404)


def error_500(request):
    return render(request, '500.html', {}, status=500)


def error_503(request):
    return render(request, '503.html', {}, status=503)


class Index(LoginRequiredMixin, View):
    template = 'index.html'

    def get(self, request):
        return HttpResponseRedirect(reverse_lazy('dashboard'))


class Home(LoginRequiredMixin, View):
    template = 'base.html'

    def get(self, request):
        return render(request, self.template)


class Dashboard(LoginRequiredMixin, View):
    template = 'dashboard.html'

    def get(self, request):
        return render(request, self.template, context_dashboard())


class Logout(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/login/')

app/frontend/templates/customer/confirm_delete.html
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 22/07/2020 17:03.
  -->
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">{{view.title}}</h4>
                    <p class="card-category">{{view.subtitle}}</p>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h3>Você tem certeza que quer deletar "{{ object }}" ?</h3>
                        <h5>Todos os itens abaixo serão excluidos!</h5>
                        {% for model_name in extra_object %} <p>{{ model_name }}</p> {% endfor %}
                        <div class="mt-3">
                            <a class="btn btn-sm btn-danger" href="{{ view.get_success_url }}">Cancelar</a>
                            <button class="btn btn-sm btn-primary mr-4" type="submit">Confirmar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/frontend/templates/customer/form.html
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 24/08/2020 15:54.
  -->

{% extends '../base/form.html' %}
{% load static %}
{% block javascript %}
<script src="{% static 'dist/libs/imask/dist/imask.min.js' %}"></script>
<script>
    $(document).ready(function(){
        var element = document.getElementById('id_cellphone');
        var maskOptions = {
          mask: '(00) 0 0000-0000'
        };
        var mask = IMask(element, maskOptions);

        var element2 = document.getElementById('id_phone');
        var maskOptions2 = {
          mask: '(00) 0000-0000'
        };
        var mask2 = IMask(element2, maskOptions2);

        var element3 = document.getElementById('id_cpf');
        if (element3) {
            var maskOptions3 = {
              mask: '000.000.000-00'
            };
            var mask3 = IMask(element3, maskOptions3);
        }

        var element4 = document.getElementById('id_cnpj');
        if (element4) {
            var maskOptions4 = {
              mask: '00.000.000/0000-00'
            };
            var mask4 = IMask(element4, maskOptions4);
        }
    });

</script>
{% endblock %}

app/frontend/templates/customer/profile.html
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 15/08/2020 15:02.
  -->
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}
{% block content %}
<div class="container-fluid">
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col-auto">
                <h2 class="page-title">
                    <a href="{{obj.get_back_url}}" rel="tooltip" title="Voltar">
                        <span class="text-primary">{{ICON_ARROW_BACK|safe}}</span>
                    </a>
                    {{obj.get_full_name}}
                    <a href="{{obj.get_edit_url}}" rel="tooltip" title="Editar">
                        <span class="text-success">{{ICON_EDIT|safe}}</span>
                    </a>
                    <a href="{{obj.get_delete_url}}" rel="tooltip" title="Deletar">
                        <span class="text-danger">{{ICON_DELETE|safe}}</span>
                    </a>
                </h2>
            </div>
            <!-- Page title actions -->
            <div class="col-auto ml-auto d-print-none">
                <a class="btn btn-sm btn-primary ml-3 d-none d-sm-inline-block"
                   href="{{obj.get_new_device_url}}">
                    {{ICON_ADD|safe}}
                    Novo Equipamento
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h3>Dados do Cliente</h3>
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    {% for k, v in obj.get_personal_to_dict.items %}
                    <tr>
                        <td>{{k}}</td>
                        <td>{{v|default_if_none:""}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <h3>Endereço do Cliente</h3>
            <div class="table-responsive mt-3">
                <table class="table table-hover table-striped">
                    {% for k, v in obj.get_address_to_dict.items %}
                    <tr>
                        <td>{{k}}</td>
                        <td>{{v|default_if_none:""}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="col-md-6">
            <h3>
                Equipamentos
                <a href="{% url 'device:create' cpk=obj.pk ctp=obj.type %}" rel="tooltip" title="Novo Equipamento">
                    <span class="text-info">{{ICON_ADD|safe}}</span>
                </a>
            </h3>
            <div class="table-responsive mt-3">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>Equipamento</th>
                        <th>Serviços</th>
                    </tr>
                    </thead>
                    {% for v in obj.devices.all %}
                    <tr>
                        <td>
                            <a href="{{v.get_absolute_url}}">
                                {{v.get_full_name}}
                            </a>
                        </td>
                        <td><span class="font-weight-bold">x{{v.order_of_services.count}}</span></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/frontend/templates/customer/view.html
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 24/08/2020 15:54.
  -->
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    {% include 'under_construction.html' %}
    <div class="row">
        {% for k,v in links.items %}
        <div class="col-md-6">
            <div class="page-header">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <h2 class="page-title">
                            {{k}}
                            <!--                            <a href="{{v.link}}" rel="tooltip" title="Novo">-->
                            <!--                                <span class="text-info">{{ICON_ADD|safe}}</span>-->
                            <!--                            </a>-->
                        </h2>
                    </div>
                </div>
            </div>
            <div class="list-group">
                {% for kk,vv in v.items %}
                {% if kk != 'config' %}
                <a class="list-group-item list-group-item-action" href="{{vv.link}}">
                    {{vv.icon|safe}}
                    {{vv.name}}
                </a>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}