app/app/urls.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/08/2020 15:46.

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('config/', include('config.urls')),
    path('device/', include('device.urls')),
    path('service/', include('service.urls')),
]

# Handling errors, but only if debug is set to False and there is another server to serve staticfiles
handler400 = 'frontend.views.error_400'
handler401 = 'frontend.views.error_401'
handler403 = 'frontend.views.error_403'
handler404 = 'frontend.views.error_404'
handler500 = 'frontend.views.error_500'
handler503 = 'frontend.views.error_503'

app/config/urls.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/08/2020 12:00.

from django.urls import path, include

from .views import *

app_name = "config"

brand_patterns = ([
                      path('', BrandView.as_view(), name='view'),
                      path('create/', BrandCreate.as_view(), name='create'),
                      path('<int:pk>/edit/', BrandEdit.as_view(), name='edit'),
                      path('<int:pk>/del', BrandDel.as_view(), name='delete'),
                  ], 'brand')
model_patterns = ([
                      path('', ModelView.as_view(), name='view'),
                      path('create/', ModelCreate.as_view(), name='create'),
                      path('<int:pk>/edit/', ModelEdit.as_view(), name='edit'),
                      path('<int:pk>/del', ModelDel.as_view(), name='delete'),
                  ], 'model')
type_patterns = ([
                     path('', TypeView.as_view(), name='view'),
                     path('create/', TypeCreate.as_view(), name='create'),
                     path('<int:pk>/edit/', TypeEdit.as_view(), name='edit'),
                     path('<int:pk>/del', TypeDel.as_view(), name='delete'),
                 ], 'type')
capacity_patterns = ([
                         path('', CapacityView.as_view(), name='view'),
                         path('create/', CapacityCreate.as_view(), name='create'),
                         path('<int:pk>/edit/', CapacityEdit.as_view(), name='edit'),
                         path('<int:pk>/del', CapacityDel.as_view(), name='delete'),
                     ], 'capacity')
city_patterns = ([
                     path('', CityView.as_view(), name='view'),
                     path('create/', CityCreate.as_view(), name='create'),
                     path('<int:pk>/edit/', CityEdit.as_view(), name='edit'),
                     path('<int:pk>/del', CityDel.as_view(), name='delete'),
                 ], 'city')
type_of_service_patterns = ([
                                path('', TypeOfServiceView.as_view(), name='view'),
                                path('create/', TypeOfServiceCreate.as_view(), name='create'),
                                path('<int:pk>/edit/', TypeOfServiceEdit.as_view(), name='edit'),
                                path('<int:pk>/del', TypeOfServiceDel.as_view(), name='delete'),
                            ], 'typeofservice')
status_service_patterns = ([
                               path('', StatusServiceView.as_view(), name='view'),
                               path('create/', StatusServiceCreate.as_view(), name='create'),
                               path('<int:pk>/edit/', StatusServiceEdit.as_view(), name='edit'),
                               path('<int:pk>/del', StatusServiceDel.as_view(), name='delete'),
                           ], 'statusservice')
device_parts_patterns = ([
                             path('', DevicePartsView.as_view(), name='view'),
                             path('create/', DevicePartsCreate.as_view(), name='create'),
                             path('<int:pk>/edit/', DevicePartsEdit.as_view(), name='edit'),
                             path('<int:pk>/del', DevicePartsDel.as_view(), name='delete'),
                         ], 'deviceparts')
urlpatterns = [
    path('', Config.as_view(), name='index'),
    path('brand/', include(brand_patterns)),
    path('model/', include(model_patterns)),
    path('type/', include(type_patterns)),
    path('capacity/', include(capacity_patterns)),
    path('city/', include(city_patterns)),
    path('typeofservice/', include(type_of_service_patterns)),
    path('statusservice/', include(status_service_patterns)),
    path('deviceparts/', include(device_parts_patterns)),
]

app/customer/urls.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 31/07/2020 14:27.
from django.urls import path, include

from .views import *

app_name = "customer"

individual_patterns = ([
                           path('', IndividualCustomerView.as_view(), name='view'),
                           path('create/', IndividualCustomerCreate.as_view(), name='create'),
                           path('<int:pk>/edit/', IndividualCustomerEdit.as_view(), name='edit'),
                           path('<int:pk>/del', IndividualCustomerDel.as_view(), name='delete'),
                       ], 'individualcustomer')

juridical_patterns = ([
                          path('', JuridicalCustomerView.as_view(), name='view'),
                          path('create/', JuridicalCustomerCreate.as_view(), name='create'),
                          path('<int:pk>/edit/', JuridicalCustomerEdit.as_view(), name='edit'),
                          path('<int:pk>/del', JuridicalCustomerDel.as_view(), name='delete'),
                      ], 'juridicalcustomer')

urlpatterns = [
    path('', Customer.as_view(), name='index'),
    path('profile/<int:pk>/<int:tp>/', CustomerProfile.as_view(), name='profile'),
    path('individual/', include(individual_patterns)),
    path('juridical/', include(juridical_patterns)),
]

app/frontend/urls.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/08/2020 15:18.

from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
]

app/base/models.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 12/08/2020 17:44.

from django.conf import settings
from django.db import models
from django.urls import reverse
from simple_history.models import HistoricalRecords

from .middleware import local


class BaseModel(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL,
                                   related_name='%(class)s_created_by', verbose_name="Criado por",
                                   help_text="Usuário que criou.")
    # updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL,
    #                                related_name='%(class)s_updated_by', verbose_name="Atualizado por",
    #                                help_text="Usuário que modificou.")
    created_in = models.DateField("criado em", auto_now_add=True, help_text="Data em que foi criado.")
    # updated_in = models.DateField("atualizado em", auto_now=True, help_text="Data em que foi atualizado.")
    history = HistoricalRecords(inherit=True)

    def save(self, *args, **kwargs):
        if self.pk is None and hasattr(local, 'user'):
            self.created_by = local.user
        # elif hasattr(local, 'user'):
        #     self.updated_by = local.user
        return super(BaseModel, self).save(*args, **kwargs)

    class Meta:
        abstract = True

    @property
    def get_delete_url(self):
        return reverse('{}:{}:delete'.format(self._meta.app_label, self._meta.model_name), kwargs={'pk': self.pk})

    @property
    def get_edit_url(self):
        return reverse('{}:{}:edit'.format(self._meta.app_label, self._meta.model_name), kwargs={'pk': self.pk})

    @property
    def get_back_url(self):
        return reverse('{}:{}:view'.format(self._meta.app_label, self._meta.model_name))

app/frontend/models.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 10/08/2020 11:56.
from django.db import models


class NotificationsMessages(models.Model):
    text = models.CharField(max_length=128, blank=True, null=True)
    link = models.CharField(max_length=128, blank=True, null=True)
    show = models.BooleanField(default=True)
    important = models.BooleanField(default=False)

app/base/views.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 17/07/2020 11:56.

# Create your views here.

app/frontend/views.py
#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/08/2020 15:42.

import logging

from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from .utils import *

logger = logging.getLogger(__name__)


def error_400(request, exception):
    logger.error("Error 400: [%s]" % exception)
    return render(request, '400.html', {}, status=400)


def error_401(request, exception):
    logger.error("Error 401: [%s]" % exception)
    return render(request, '401.html', {}, status=401)


def error_403(request, exception):
    logger.error("Error 403: [%s]" % exception)
    return render(request, '403.html', {}, status=403)


def error_404(request, exception):
    logger.error("Error 404: [%s]" % exception)
    return render(request, '404.html', {}, status=404)


def error_500(request):
    return render(request, '500.html', {}, status=500)


def error_503(request):
    return render(request, '503.html', {}, status=503)


class Index(LoginRequiredMixin, View):
    template = 'index.html'

    def get(self, request):
        return HttpResponseRedirect(reverse_lazy('dashboard'))


class Home(LoginRequiredMixin, View):
    template = 'base.html'

    def get(self, request):
        return render(request, self.template)


class Dashboard(LoginRequiredMixin, View):
    template = 'dashboard.html'

    def get(self, request):
        return render(request, self.template, context_dashboard())


class Logout(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/login/')

app/frontend/templates/401.html
{% extends 'base.html' %}
{% block body_html %}
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 15/08/2020 15:46.
  -->

<body class="antialiased border-top-wide border-primary d-flex flex-column">
<div class="flex-fill d-flex align-items-center justify-content-center">
    <div class="container-tight py-6">
        <div class="empty">
            <div class="empty-icon">
                <div class="display-4">401</div>
            </div>
            <p class="empty-title h3">Oops… Aconteceu alguma coisa</p>
            <p class="empty-subtitle text-muted">
                Você não possui autorização para acessar essa página
            </p>
            <div class="empty-action">
                <a class="btn btn-primary" href="./.">
                    <svg class="icon" fill="none" height="24" stroke="currentColor" stroke-linecap="round"
                         stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M0 0h24v24H0z" stroke="none"/>
                        <line x1="5" x2="19" y1="12" y2="12"/>
                        <line x1="5" x2="11" y1="12" y2="18"/>
                        <line x1="5" x2="11" y1="12" y2="6"/>
                    </svg>
                    Take me home
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Libs JS -->
<script src="{% static 'dist/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<!-- Tabler Core -->
<script src="{% static 'dist/js/tabler.min.js' %}"></script>
<script>
      document.body.style.display = "block"

</script>
</body>
{% endblock %}

app/frontend/templates/503.html
{% extends 'base.html' %}
{% block body_html %}
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 15/08/2020 15:46.
  -->

<body class="antialiased border-top-wide border-primary d-flex flex-column">
<div class="flex-fill d-flex align-items-center justify-content-center">
    <div class="container-tight py-6">
        <div class="empty">
            <div class="empty-icon">
                <div class="display-4">503</div>
            </div>
            <p class="empty-title h3">Oops… Aconteceu alguma coisa</p>
            <p class="empty-subtitle text-muted">
                Nosso serviço não está disponível no momento
            </p>
            <div class="empty-action">
                <a class="btn btn-primary" href="./.">
                    <svg class="icon" fill="none" height="24" stroke="currentColor" stroke-linecap="round"
                         stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M0 0h24v24H0z" stroke="none"/>
                        <line x1="5" x2="19" y1="12" y2="12"/>
                        <line x1="5" x2="11" y1="12" y2="18"/>
                        <line x1="5" x2="11" y1="12" y2="6"/>
                    </svg>
                    Take me home
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Libs JS -->
<script src="{% static 'dist/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<!-- Tabler Core -->
<script src="{% static 'dist/js/tabler.min.js' %}"></script>
<script>
      document.body.style.display = "block"



</script>
</body>
{% endblock %}

app/frontend/templates/base.html
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 15/08/2020 15:28.
  -->

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1, viewport-fit=cover" name="viewport"/>
    <meta content="ie=edge" http-equiv="X-UA-Compatible"/>
    <title>{{NAME_OF_ENTERPRISE}}</title>
    <link crossorigin href="https://fonts.gstatic.com/" rel="preconnect">
    <meta content="#206bc4" name="msapplication-TileColor"/>
    <meta content="#206bc4" name="theme-color"/>
    <meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"/>
    <meta content="yes" name="apple-mobile-web-app-capable"/>
    <meta content="yes" name="mobile-web-app-capable"/>
    <meta content="True" name="HandheldFriendly"/>
    <meta content="320" name="MobileOptimized"/>
    <meta content="noindex,nofollow,noarchive" name="robots"/>
    <link href="{% static 'favicon.ico' %}" rel="icon" type="image/x-icon"/>
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon" type="image/x-icon"/>
    <!-- CSS files -->
    <link href="{% static 'dist/libs/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'dist/css/tabler.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'custom/css/custom-css.css' %}" rel="stylesheet"/>
    <!--    <link href="{% static 'dist/css/demo.min.css' %}" rel="stylesheet"/>-->
    <style>
      body {
      	display: none;
      }

    </style>
    <!--  Block of links  -->
    {% block links %}{% endblock %}
</head>
{% block body_html %}
<body class="antialiased">
{% block sidebar %}{% include "sidebar.html" %}{% endblock %}
<div class="page">
    <div class="content" id="content">
        {% block content %}{% include "dashboard.html" %}{% endblock %}
        {% block footer %}{% include "footer.html" %}{% endblock %}
    </div>
</div>
<!-- Libs JS -->
<script src="{% static 'dist/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'dist/libs/jquery/dist/jquery.slim.min.js' %}"></script>
<script src="{% static 'dist/libs/apexcharts/dist/apexcharts.min.js' %}"></script>
<!--<script src="{% static 'dist/libs/jqvmap/dist/jquery.vmap.min.js' %}"></script>-->
<!--<script src="{% static 'dist/libs/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>-->
<script src="{% static 'dist/libs/peity/jquery.peity.min.js' %}"></script>
<!-- Tabler Core -->
<script src="{% static 'dist/js/tabler.min.js' %}"></script>

<script>
  document.body.style.display = "block"
</script>
{% block javascript %}{% endblock %}
</body>
{% endblock %}
</html>

app/frontend/templates/footer.html
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 12/08/2020 17:56.
  -->

<footer class="footer footer-transparent">
    <div class="container">
        <div class="row text-center align-items-center flex-row-reverse">
            <div class="col-lg-auto ml-lg-auto">
                <ul class="list-inline list-inline-dots mb-0">
                    <li class="list-inline-item"><a class="link-secondary" href="./docs/index.html">Documentação</a>
                    </li>
<!--                    <li class="list-inline-item"><a class="link-secondary" href="./faq.html">FAQ</a></li>-->
<!--                    <li class="list-inline-item"><a class="link-secondary" href="https://github.com/tabler/tabler"-->
<!--                                                    target="_blank">Source code</a></li>-->
                </ul>
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0">
                Copyright © 2020
                <a class="link-secondary" href="https://iuasse.com.br">Iuasse, Serviços Digitais</a>.
                Todos os direitos reservados.
            </div>
        </div>
    </div>
</footer>

app/frontend/templates/sidebar.html
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 21/08/2020 17:29.
  -->
{% load static %}
<aside class="navbar navbar-vertical navbar-expand-lg navbar-dark">
    <div class="container">
        <button class="navbar-toggler" data-target="#navbar-menu" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand navbar-brand-autodark" href="{% url 'dashboard' %}">
            <img alt="{{NAME_OF_ENTERPRISE}}" class="navbar-brand-image" src="{% static 'logo.svg' %}">
        </a>
        <!-- Actions when on cellphone -->
        <!--        <div class="navbar-nav flex-row d-lg-none">-->
        <!--            <div class="nav-item dropdown d-none d-md-flex mr-3">-->
        <!--                <a class="nav-link px-0" data-toggle="dropdown" href="#" tabindex="-1">-->
        <!--                    <svg class="icon" fill="none" height="24" stroke="currentColor" stroke-linecap="round"-->
        <!--                         stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24"-->
        <!--                         xmlns="http://www.w3.org/2000/svg">-->
        <!--                        <path d="M0 0h24v24H0z" stroke="none"/>-->
        <!--                        <path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6"/>-->
        <!--                        <path d="M9 17v1a3 3 0 0 0 6 0v-1"/>-->
        <!--                    </svg>-->
        <!--                    <span class="badge bg-red"></span>-->
        <!--                </a>-->
        <!--                <div class="dropdown-menu dropdown-menu-right dropdown-menu-card">-->
        <!--                    <div class="card">-->
        <!--                        <div class="card-body">-->
        <!--                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus ad amet consectetur-->
        <!--                            exercitationem fugiat in ipsa ipsum, natus odio quidem quod repudiandae sapiente. Amet-->
        <!--                            debitis et magni maxime necessitatibus ullam.-->
        <!--                        </div>-->
        <!--                    </div>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--            <div class="nav-item dropdown">-->
        <!--                <a class="nav-link d-flex lh-1 text-reset p-0" data-toggle="dropdown" href="#">-->
        <!--                    <span class="avatar" style="background-image: url({% static 'avatars/000m.jpg' %})"></span>-->
        <!--                    <div class="d-none d-xl-block pl-2">-->
        <!--                        <div>Paweł Kuna</div>-->
        <!--                        <div class="mt-1 small text-muted">UI Designer</div>-->
        <!--                    </div>-->
        <!--                </a>-->
        <!--                <div class="dropdown-menu dropdown-menu-right">-->
        <!--                    <a class="dropdown-item" href="#">-->
        <!--                        <svg class="icon dropdown-item-icon" fill="none" height="24" stroke="currentColor"-->
        <!--                             stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"-->
        <!--                             width="24" xmlns="http://www.w3.org/2000/svg">-->
        <!--                            <path d="M0 0h24v24H0z" stroke="none"/>-->
        <!--                            <path d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/>-->
        <!--                            <circle cx="12" cy="12" r="3"/>-->
        <!--                        </svg>-->
        <!--                        Action-->
        <!--                    </a>-->
        <!--                    <a class="dropdown-item" href="#">-->
        <!--                        <svg class="icon dropdown-item-icon" fill="none" height="24" stroke="currentColor"-->
        <!--                             stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"-->
        <!--                             width="24" xmlns="http://www.w3.org/2000/svg">-->
        <!--                            <path d="M0 0h24v24H0z" stroke="none"/>-->
        <!--                            <path d="M9 7 h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3"/>-->
        <!--                            <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3"/>-->
        <!--                            <line x1="16" x2="19" y1="5" y2="8"/>-->
        <!--                        </svg>-->
        <!--                        Another action-->
        <!--                    </a>-->
        <!--                    <div class="dropdown-divider"></div>-->
        <!--                    <a class="dropdown-item" href="#">-->
        <!--                        <svg class="icon dropdown-item-icon" fill="none" height="24" stroke="currentColor"-->
        <!--                             stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"-->
        <!--                             width="24" xmlns="http://www.w3.org/2000/svg">-->
        <!--                            <path d="M0 0h24v24H0z" stroke="none"/>-->
        <!--                            <line x1="12" x2="12" y1="5" y2="19"/>-->
        <!--                            <line x1="5" x2="19" y1="12" y2="12"/>-->
        <!--                        </svg>-->
        <!--                        Separated link</a>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--        </div>-->
        <!-- Menu links -->
        <div class="collapse navbar-collapse" id="navbar-menu">
            <ul class="navbar-nav pt-lg-3">
                <li class="nav-item {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'dashboard' %}">
                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                          {{ICON_DASHBOARD|safe}}
                        </span>
                        <span class="nav-link-title">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item {% if 'customer' in request.path  or 'device' in request.path and 'config' not in request.path or 'service' in request.path and 'config' not in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'customer:index' %}">
                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                          {{ICON_PERSON|safe}}
                        </span>
                        <span class="nav-link-title">Clientes</span>
                    </a>
                </li>
                <li class="nav-item {% if 'config' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'config:index' %}">
                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                          {{ICON_SETTINGS|safe}}
                        </span>
                        <span class="nav-link-title">Configurações</span>
                    </a>
                </li>
                <li class="nav-item mt-auto">
                    <a class="nav-link" data-target="#modal-logout" data-toggle="modal" href="#">
                        <span class="nav-link-icon d-md-none d-lg-inline-block">
                          {{ICON_LOGOUT|safe}}
                        </span>
                        <span class="nav-link-title">Sair</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</aside>
<div aria-hidden="true" class="modal modal-blur fade" id="modal-logout" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Sair ?</h5>
                <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                    <svg class="icon" fill="none" height="24" stroke="currentColor" stroke-linecap="round"
                         stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M0 0h24v24H0z" stroke="none"/>
                        <line x1="18" x2="6" y1="6" y2="18"/>
                        <line x1="6" x2="18" y1="6" y2="18"/>
                    </svg>
                </button>
            </div>
            <div class="modal-body">
                Você quer sair do sistema ?
            </div>
            <div class="modal-footer">
                <button class="btn btn-white mr-auto" data-dismiss="modal" type="button">Fechar</button>
                <a class="btn btn-primary" href="{% url 'logout' %}" type="button">Sim</a>
            </div>
        </div>
    </div>
</div>

app/frontend/templates/under_construction.html
<!--
  ~ Created by Alex Matos Iuasse.
  ~ Copyright (c) 2020.  All rights reserved.
  ~ Last modified 14/08/2020 19:56.
  -->

<!--<div class="col-12">-->
<!--    <hr>-->
<!--    <h3 class="text-center">-->
<!--        Em Desenvolvimento <span class="text-danger">{{ICON_BUG|safe}}</span>-->
<!--    </h3>-->
<!--    <h4 class="text-center">-->
<!--        <span class="text-warning">{{ICON_TRIANGLE_ALERT|safe}}</span>-->
<!--        Atenção, versão apenas de teste, os dados podem ser apagados!-->
<!--    </h4>-->
<!--    <p class="small text-center">Caso você encontre algum erro, por favor me notifique!</p>-->
<!--    <hr>-->
<!--</div>-->